name: Run Tests

on: push

jobs:
  unit-test-and-style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup caching
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-cache-
      - name: Install dependencies
        run: |
          yarn
      - name: Run tests
        run: |
          yarn lint
          yarn test
