name: Test and Publish

on: push

jobs:
  unit-test-and-style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup caching
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-cache-
      - name: Install dependencies
        run: |
          yarn
      - name: Run tests
        run: |
          yarn lint
          yarn test
  build-and-publish:
    needs: unit-test-and-style-check
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - name: Setup caching
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-cache-
      - name: Install dependencies
        run: |
          yarn
      - name: Build library
        run: |
          yarn build
      - name: Prepare for publishing
        id: prepare_publish
        run: |
          export ref='${{ github.ref }}'
          export tag=${ref:11}
          echo "::set-output name=tag::$tag"
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          TAG: ${{ steps.prepare_publish.outputs.tag }}
        run: |
          yarn publish --new-version $TAG -tag alpha
